### ISSUE TITLE
bug: 19 out of 31 tests are failing. 

### ISSUE THREAD

**Issue by kirankotari** [beelit94/python-terraform#121]
Full test summary: [pytest GitHub Action](https://github.com/beelit94/python-terraform/runs/6606454060?check_suite_focus=true#step:5:49)
=========================== short test summary info ============================
FAILED test/test_terraform.py::TestTerraform::test_cmd[<lambda>-Plan: 0 to add, 0 to change, 0 to destroy.-0-False--var_to_output]
FAILED test/test_terraform.py::TestTerraform::test_cmd[<lambda>--0-False--var_to_output]
FAILED test/test_terraform.py::TestTerraform::test_apply[var_to_output-variables0-None-test_output=test-options0]
FAILED test/test_terraform.py::TestTerraform::test_apply[var_to_output-variables1-None-test_list_output=["c","d",]-options1]
FAILED test/test_terraform.py::TestTerraform::test_apply[var_to_output-variables2-None-test_map_output={"c"="c""d"="d"}-options2]
FAILED test/test_terraform.py::TestTerraform::test_apply[var_to_output-variables3-var_to_output/test_map_var.json-test_map_output={"e"="e""f"="f"}-options3]
FAILED test/test_terraform.py::TestTerraform::test_apply[var_to_output-variables4-None-\x1b[0m\x1b[1m\x1b[32mApplycomplete!-options4]
FAILED test/test_terraform.py::TestTerraform::test_apply_with_var_file - pyth...
FAILED test/test_terraform.py::TestTerraform::test_override_default[var_to_output-variables0]
FAILED test/test_terraform.py::TestTerraform::test_output[True] - python_terr...
FAILED test/test_terraform.py::TestTerraform::test_output[False] - python_ter...
FAILED test/test_terraform.py::TestTerraform::test_destroy - python_terraform...
FAILED test/test_terraform.py::TestTerraform::test_plan[vars_require_input-variables0-1]
FAILED test/test_terraform.py::TestTerraform::test_create_workspace_with_args
FAILED test/test_terraform.py::TestTerraform::test_set_workspace_with_args - ...
FAILED test/test_terraform.py::TestTerraform::test_show_workspace - python_te...
FAILED test/test_terraform.py::TestTerraform::test_show_workspace_with_no_color
FAILED test/test_terraform.py::TestTerraform::test_delete_workspace - python_...
FAILED test/test_terraform.py::TestTerraform::test_delete_workspace_with_args
======================== 19 failed, 12 passed in 6.19s =========================

**Comment by kirankotari** [comment]
To install terraform to run test cases
```
permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

```
